import {  Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navabr";
import Header from "@/components/Header";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`  h-full antialiased`}
    >
      <body className={`min-h-full flex flex-col ${poppins.variable}`}>
        {/* <Header></Header>
        <Navbar></Navbar> */}
        
        {children}
      </body>
    </html>
  );
}
